apiVersion: v1
kind: Service
metadata:
  name: {{ include "quik.fullname" . }}
  labels:
    {{- include "quik.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  selector:
    {{- include "quik.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
    {{- if .Values.service.exposeAdmin }}
    - name: admin
      port: {{ .Values.config.admin.port }}
      targetPort: admin
      protocol: TCP
    {{- end }}
